### ISSUE TITLE
Problem installing

### ISSUE THREAD

**Issue by pmousse** [sketchfab/blender-plugin#10]
When I install the add-on in Blender 2.82, it says module installed, but it doesn't show up in the addons list.

**Comment by loicSketchfab** [comment]
Hi ! :wave: 

That's strange, I just tested with a fresh install of blender 2.82a for linux (the current stable version available on the download page: https://www.blender.org/download/), and the addon installs smoothly...

![image](https://user-images.githubusercontent.com/52042414/78977773-f8b0f680-7b18-11ea-9eab-c75886ae4f13.png)

* Did you use the latest version of the addon (1.2.1), available here: https://github.com/sketchfab/blender-plugin/releases/tag/1.2.1 ? 

* If you are sure you are not using a newer version of Blender (such as the experimental 2.83 alpha), could you try to give us more info? In particular the version of Blender you are using and on which OS.

* Also, it could be hepful to have the output of the system console when you activate the addon, if there is one (on Windows you can display it through Window -> System console, while you'll have to run Blender through a terminal on Mac or linux to display it).

Thanks for your report.

**Comment by jimiblender** [comment]
Hi there,
I'm having a similar problem. When I go to Edit-Preferences, Install and click on the zip file, then Install Add-on, it does nothing. I've tried numerous times. I assume it doesn't need to be unzipped, because the only other add-on I've installed like this (BlenderGIS) unzipped itself. I must be doing something wrong, any ideas?
Cheers.

**Comment by notbyhalf** [comment]
I was having the same problem BUT it was all my fault. I had downloaded the source as a zip instead of the release. The link for the release installs no trouble at all.

https://github.com/sketchfab/blender-plugin/releases/tag/1.2.1

**Comment by jimiblender** [comment]
Hi there,

Thanks for your help, but I can't get either option to work. Just to
clarify: I've downloaded both 'sketchfab-plugin-1-2-1.zip' (the release?)
and 'source code zip' and when I go to Edit-Preferences-Install it just
does nothing, and the Sketchfab tab fails to appear. Is there some weird
hidden step I'm missing?

Cheers,
Jimi.

**Comment by notbyhalf** [comment]
Hi Jimi,

That should be all there is to it. When I was first having trouble, I took note of where the addon was installed (when you install from ZIP it tells you at the bottom of the blender window the path to the addon) and I deleted it just to be sure I had a clean install.

In my case on the mac, the addons are being installed into:
/Users/laurenceyates/Library/Application Support/Blender/2.82/scripts/addons

After installing, it was just a case of enabling the Sketchfab addon from the list and the tab appear. Maybe a factory reset will help. I don't have any other tips, sorry.

Laurence.

**Comment by jimiblender** [comment]
Hi Laurence,

Thanks a lot for trying to help. Because my experience of installing add-ons like this only extended to the BlenderGIS one I have installed, I did it the same way. I had no idea where they were supposed to go, so I downloaded it and put it in a folder of my own creation where I keep my project files. As this has never caused a problem with BlenderGIS I thought it would work for this, but I'll try what you suggested and see if it works. Maybe that makes me the biggest noob ever, but as I'm not a developer, just a user, everything is trial and error!

Thanks again,
Jimi.

**Comment by jimiblender** [comment]
Hi again,
Well my Blender files are all installed in Snaps for some reason, maybe that's the new way of doing it automatically. I have a folder called ...2.82/scripts/addons, but I can't move the downloaded zip files into it, even when running 'sudo nautilus'. Would it let me do it from the terminal do you think? If not, how are you supposed to put program files in the right place?
Cheers,
Jimi.

**Comment by raindropsfromsky** [comment]
I am having the same problem. 

Incidentally I get two different zip files depending upon the download method:

1. If I visit the [main page](https://github.com/sketchfab/blender-plugin), I see a large green button named **Clone Or download**. I click on it and then select the **Download ZIP** option. Here, I get a **master.zip** file.
2. If I follow the Code >Releases path, I land up on the [Releases](https://github.com/sketchfab/blender-plugin/releases) page. Here, a [different zip file](https://github.com/sketchfab/blender-plugin/releases/download/1.2.1/sketchfab-plugin-1-2-1.zip) is posted under the "Assets" list.

I followed both paths, and tried with both files. I cannot install the addon using both methods.
There is no error during installation, but after the installation, the addon does not appear at all.

Reporting for Blender 2.90 alpha, dated 23-4-2020; running on Windows 10 Home, 64 bits.
I have i3 8130U CPU with 12 GB DDR4 RAM.

**Comment by jimiblender** [comment]
Hi Narayan,

I fixed my problem by reinstalling Blender completely, as domlysz
suggested. I did that because I was also having problems installing a
Sketchfab add-on, so I thought it might work. I recommend installing via
Snap (https://snapcraft.io/blender) because it's the easiest and most
effective way I've found. The thing you'll maybe have to do is rename (or
delete, if you're confident about what you're doing) the current .config
folder which Blender is using to store certain files. When I did that and
reinstalled Blender 2.82a (still the current stable version I think) it
created a new .config folder within Home/Snaps/Blender and when I installed
the BlenderGIS add-on again in Blender, everything worked fine. Maybe
downgrade from 2.90 to 2.82a?

I didn't understand why Blender was installed in Snap and other files
appeared in .config, but a developer friend told me it was normal, and that
the program files would be in Snap, as .config isn't used for binary files,
just configuration stuff which multiple users of a machine might want to
set up differently (imagine one user has need of GIS and another is an
animator with different priorities).

I hope that helps, and if you need anything else clarified, just ask!

Cheers,
Jimi.

**Comment by raindropsfromsky** [comment]
Ah, well.

I am using Windows, so none of the above factors apply. But I deleted the 2.90 alpha folder and downloaded the latest version today, and unzipped it. This time it could install the addon. So probably this is the problem with 2.90 alpha.

**Comment by jimiblender** [comment]
Hi Narayan,

Sorry about that, I completely spaced on your OS. All the same I suppose
Blender automatically creates an equivalent .config folder for each new
version, or else it would be hard to determine what to erase when you
remove an older one.

Glad you got it working!

**Comment by LordTremel** [comment]
I read through the rest of the comments but I'm not sure what my problem is. I install the addon but it doesn't seem to do anything. What is it supposed to do?

**Comment by jimiblender** [comment]
It creates a direct importer for Sketchfab models, complete with materials,
and it also lets you browse the collection as you would on their site.

**Comment by LordTremel** [comment]
ok umm...… the importer should be in the import tab right? because im not getting anything there.

**Comment by jimiblender** [comment]
Yeah, it should appear under the View tab. I've attached a screenshot which
should hopefully appear, to clarify where I see it.

**Comment by jimiblender** [comment]
Sorry, here you go. I responded in gmail like a noob and it didn't appear.

![Sketchfab tab](https://user-images.githubusercontent.com/63593073/80808784-92bc0a00-8bc0-11ea-9611-2a0680cc39f5.png)

**Comment by LordTremel** [comment]
oh ok thank you

**Comment by Jessika07** [comment]
i have windows 10, Blender version 2.83 (from Steam).  i installed the add on, activate it in preference but i don't see the tab.  I tried closing the program and restart.  Should it work with that version?
