### ISSUE TITLE
3.5

### ISSUE THREAD

**Issue by miklas206** [sketchfab/blender-plugin#108]
i get this error when installing on blender version 3.5 worked fine on 3.4
![Blender error](https://user-images.githubusercontent.com/72841842/231019845-66bcf4a3-accb-4de4-9a52-deefe8ae4544.png)

**Comment by sirschnabeltier** [comment]
Hey there!
Had the same issue with 3.5, but figured it was due to version incompatibility. Proceeded to install 3.3.5, then 3.3.1, which was supposedly supported, and still had the same issue as you.

The "PermissionError" in the Error message threw me off and I figured out a solution; 

- [ ] Run Blender as Administrator

This allowed installation/activation in 3.5 for me; haven't tested the addon itself yet, though.
