### ISSUE TITLE
Unable to log in.

### ISSUE THREAD

**Issue by NuriArchive** [sketchfab/blender-plugin#121]
<img width="1280" alt="image" src="https://github.com/sketchfab/blender-plugin/assets/124021114/a940c143-826e-4968-aa1b-dd26a6d5466c">

I already have a sketchfab account (Google login)
After installing Sketchpe add-on, I try to log in, but even though I have an account, I fail to log in.
Is Google account impossible?
Please allow me to add-on Google login sketchfab account.

**Comment by NuriArchive** [comment]
I found the API Key and entered it, and it seems to be proceeding to the next step.
Do I not necessarily have to log in to sketchfab?

**Comment by NuriArchive** [comment]
<img width="1280" alt="image" src="https://github.com/sketchfab/blender-plugin/assets/124021114/bb14b5d1-f85a-4406-ad51-b9781bf750e7">

I imported it, but I can't see it, so it's no use changing the scale.

**Comment by PadreZippo** [comment]
You can now authenticate the plugin using your API Token instead of email + password for cases when you use a third-party identity provider such as Google.

![image](https://github.com/sketchfab/blender-plugin/assets/7097291/4925856a-67a6-4370-9e77-ff59295c20c6)

You can find your API Token here: https://sketchfab.com/settings/password
