### ISSUE TITLE
Cannot Retrieve Information for this model when Pressing Import Model

### ISSUE THREAD

**Issue by MrAlphabrine** [sketchfab/blender-plugin#123]
Hello So This error pops up whenever i try to import a model using the "Import From URL" Option, Anyone has a solution for this?

**Comment by loicEpicGames** [comment]
Hey @MrAlphabrine and @Akame0203 

Could you please try to install this .zip ([sketchfab-plugin-1-6-1.zip](https://github.com/sketchfab/blender-plugin/files/13673568/sketchfab-plugin-1-6-1.zip)) instead of the previous one (after deactivating/uninstalling the existing addon) ?

I fixed some issue making it impossible to use this option, this new version should hopefully do the trick to allow to import models from URLs 🤞 

I'll publish a hotfix following if you can confirm you manage to import models from their uurl with that.
