### ISSUE TITLE
Upload from blender fails

### ISSUE THREAD

**Issue by bsrunnels** [sketchfab/blender-plugin#131]
Uploading using the blender plugin fails. It appears to upload correctly, but then cannot be viewed online. The viewer says "Processing failed" and there is an option to "Reprocess model now", but this does nothing.

My configuration:
Blender 4.1.1
OS: Ubuntu 20.04 LTS
Plugin version: 1.6.1
What I am trying to upload: the default blender cube.

**Comment by PadreZippo** [comment]
We don't currently support processing .blend files created in Blender 4.x. We hope to get that fixed in the future, after the transition of Sketchfab to Fab. For now, we recommend either exporting and uploading one of our other supported file formats such as GLB, or you can switch to using Blender 3.6 LTS.
