### ISSUE TITLE
sketch fab imports black textures 

### ISSUE THREAD

**Issue by DONNNIEX** [sketchfab/blender-plugin#19]
certain models that import on blender have black covering 50% of the model.
![eye](https://user-images.githubusercontent.com/76064139/102250189-daca3b80-3ec8-11eb-9420-43f919d6ce7a.png)

**Comment by PadreZippo** [comment]
Hmm. Can you share the model URL?

**Comment by NIXOYE** [comment]
This has been happening for a lot of models and some models are transparent and when you change the blend mode to opaque its fully black with huge blooms of random colors

**Comment by loicSketchfab** [comment]
Hi @NIXOYE .

This behaviour should be fixed in the latest release of the addon: https://github.com/sketchfab/blender-plugin/releases/tag/1.3.0

It was due to normal maps being read as alpha textures, causing rather strange results...
Should work now though, let us know if this does not !

![image](https://user-images.githubusercontent.com/52042414/102909903-f362c480-4479-11eb-8e9a-333560a0e53a.png)

**Comment by NIXOYE** [comment]
@loicSketchfab thanks for the fix! There seems to be a similar glitch with this model. It's impoting with alpha blend as it blend mode. It seems like its supposed to be using opaque as its blend mode

https://sketchfab.com/3d-models/igloo-86cf6c480f444787a706effe394d0b8e

**Comment by gmxv** [comment]
what worked for me was, when upload the model onto sketchfab in the general section of the 3d settings there is a "vertex color" option which i found to be automatically on and when i turned it off my model was no longer black 
![image_2024-09-06_133938560](https://github.com/user-attachments/assets/f3a9d664-7aa8-4bd7-a0d6-40f8b1b31af7)
