### ISSUE TITLE
I have multiple errors with the new version - and it is not loading in any panel

### ISSUE THREAD

**Issue by onelsonic** [sketchfab/blender-plugin#6]
Warning: class SketchfabExportProps contains a property which should be an annotation!
	C:\Users\devWin10\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\sketchfab-plugin-1-2-1\__init__.py:1630

**Comment by loicSketchfab** [comment]
Hi @onelsonic , and thanks for reporting !

#### Concerning the "Warning: class ... contains a property which should be an annotation" problem
those are just some warnings, you are not to worry about them: they are due to the fact that the addon is meant to work with 2.79 and 2.8, but the preferred way to define properties in Python has changed between the two versions. We chose a way which works for both, but triggers those warnings.
We'll probably remove then as soon as possible though !

#### Add-on not loading ?
You say that the add-on is not loading in any panel: are you sure that you looked in the "Properties" panel (the one on the right, which you can open with "N") ?
In the previous version, the addon was indeed located in the "Tools" panel (in the left, opened with "T"), that might be the cause of the confusion.
![](https://user-images.githubusercontent.com/52042414/64157665-66849980-ce37-11e9-9806-c74bb1476987.jpg)

I saw that you closed the issue, so I guess (hope) that you found the add-on ? Otherwise feel free to re-open it, and maybe paste some screenshots and more logs so that we can help you.
